### ISSUE TITLE
Add supported architectures tags to each one

### ISSUE THREAD

**Issue by thewan056** [petersem/dockerholics#12]
I know its extra work, but I hope you could add supported architectures next to each item to easily tell whether do they support arm or not, besides x86.

**Comment by modem7** [comment]
I'd say the amount of work this would take would be quite significant vs the benefits incurred, and there is no easy way of automating this, unfortunately. 

@petersem Thoughts?

**Comment by modem7** [comment]
Closing as currently this is unrealistic to implement.
